Also update old-style repository (headers/ directory) as well as new.
git-svn-id: http://svn.code.sf.net/p/gratia/svn/trunk/probe@744 c85a5f45-a5f3-44fc-b02c-7891c381c519

diff --git a/build/build_all b/build/build_all
--- a/build/build_all
+++ b/build/build_all
@@ -158,6 +158,12 @@ if (( $status == 0 )) && (( ${publish:-0} )); then
       echo \"Unable to find createrepo command to update yum repository metadata\" 1>&2
       exit 1
     fi
+    if type -p yum-arch; then
+      yum-arch \"${publish_dir}/RPMS\"
+    else
+      echo \"Unable to find yum-arch command to update old-style yum repository metadata\" 1>&2
+      exit 1
+    fi
   fi"
   status=$?
 else
