Fix publisshing and yum cache updating.
git-svn-id: http://svn.code.sf.net/p/gratia/svn/trunk/probe@592 c85a5f45-a5f3-44fc-b02c-7891c381c519

diff --git a/build/build_all b/build/build_all
--- a/build/build_all
+++ b/build/build_all
@@ -44,7 +44,7 @@ EOF
   exit 1
 }
 
-while getopts :hd:r:s:pP OPT; do
+while getopts :hYd:r:s:pP OPT; do
     case $OPT in
 	d)
             if [[ -n "$defines" ]]; then
@@ -139,28 +139,29 @@ else
   exit $status
 fi
 
+publish_host="fnalu.fnal.gov"
 publish_dir=/afs/fnal.gov/files/expwww/gratia/html/Files/probe
 yum_cache=/afs/fnal.gov/files/expwww/gratia/yum-repo-cache
 
 if (( $status == 0 )) && (( ${publish:-0} )); then
   echo "Publishing files to AFS for web access ..." 1>&2
-  cp -pv `find "${rpmbuild_top}"/RPMS -name "gratia-probe*-$version-$release.*.rpm"` \
-   ${publish_dir}/RPMS/ && \
-  cp -pv "${rpmbuild_top}/SRPMS/gratia-probe-$version-$release.src.rpm" \
-   "${publish_dir}/SRPMS/"
+  scp -p `find "${rpmbuild_top}"/RPMS -name "gratia-probe*-$version-$release.*.rpm"` \
+   "${publish_host}:${publish_dir}/RPMS/" && \
+  scp -p "${rpmbuild_top}/SRPMS/gratia-probe-$version-$release.src.rpm" \
+   "${publish_host}:${publish_dir}/SRPMS/"
   status=$?
+  ssh ${publish_host} "
   if (( $status == 0 )) && (( ${yum:-0} )); then
 		if type -p createrepo; then
-      createrepo -c "${yum_cache}" -p "${publish_dir}/RPMS"
-  status=$?
+      createrepo -c \"${yum_cache}\" -p \"${publish_dir}/RPMS\"
     else
-      echo "Unable to find createrepo command to update yum repository metadata" 1>&2
+      echo \"Unable to find createrepo command to update yum repository metadata\" 1>&2
       exit 1
     fi
-  fi
+  fi"
+  status=$?
 else
   exit $status
 fi
 
 exit $status
-
